### ISSUE TITLE
deb build failed

### ISSUE THREAD

**Issue by ghost** [CBPP/cbpp-configs#8]
Hello dear Developer!

What could be the problem?

`/home/cbpp/buildenv/root/cbpp-configs/cbpp-configs/debian/cbpp-configs.install: 1: /home/cbpp/buildenv/root/cbpp-configs/cbpp-configs/debian/cbpp-configs.install: data/boot: Permission denied
dh_install: debian/cbpp-configs.install (executable config) returned exit code 126
debian/rules:22: recipe for target 'binary' failed
make: *** [binary] Error 126`

**Comment by computermouth** [comment]
There's a few ways to build debian packages. Could I ask what your current incantation is?

For example `dpkg-buildpackage -us -uc` works just fine for me.
